# Generated by Django 3.1.5 on 2021-04-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=70)),
                ('item_views', models.IntegerField(blank=True, null=True)),
                ('item_location', models.CharField(max_length=70)),
                ('item_sellorname', models.CharField(db_column='item_sellorName', max_length=70)),
                ('item_sellorid', models.CharField(blank=True, db_column='item_sellorId', max_length=70, null=True)),
                ('item_date', models.DateTimeField(blank=True, null=True)),
                ('item_price', models.IntegerField(blank=True, null=True)),
                ('item_detail', models.CharField(blank=True, max_length=300, null=True)),
                ('item_img', models.CharField(blank=True, max_length=1, null=True)),
                ('item_status', models.CharField(blank=True, max_length=20, null=True)),
                ('item_dealtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ITEM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(blank=True, max_length=50, null=True)),
                ('search_category', models.CharField(blank=True, max_length=50, null=True)),
                ('search_keyword', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'SEARCH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelledItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=70)),
                ('item_location', models.CharField(max_length=70)),
                ('item_sellorid', models.CharField(blank=True, db_column='item_sellorId', max_length=70, null=True)),
                ('item_price', models.IntegerField(blank=True, null=True)),
                ('item_img', models.CharField(blank=True, max_length=1, null=True)),
                ('item_status', models.CharField(blank=True, max_length=20, null=True)),
                ('item_dealtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SELLED_ITEM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_location', models.CharField(max_length=50)),
                ('user_phonenumber', models.CharField(db_column='user_phoneNumber', max_length=20)),
                ('user_sell_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_caution', models.IntegerField(blank=True, null=True)),
                ('user_gender', models.CharField(max_length=1)),
                ('user_date', models.DateTimeField(blank=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=30, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'USER_DETAIL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
