# Generated by Django 3.2 on 2021-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_no', models.IntegerField(primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=50)),
                ('user_location', models.CharField(max_length=20)),
                ('user_gender', models.CharField(max_length=20)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('user_birthdate', models.DateTimeField(max_length=9)),
                ('user_caution', models.IntegerField(blank=True, null=True)),
                ('user_sell_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
